### ISSUE TITLE
Bug: 插件在 Windows Server 2022 系统下版本号显示错误

### ISSUE THREAD

**Issue by hakureireimusama** [KomoriDev/nonebot-plugin-kawaii-status#1]
我用的系统是Windowssever2022，他输出的是Windows10，这个是需要设置参数，还是他自动检测的？
还有希望可以添加自定义图片或者css的功能~

**Comment by KomoriDev** [comment]
> 我用的系统是Windowssever2022，他输出的是Windows10，这个是需要设置参数，还是他自动检测的？

这是因为 Windows Server 2022（以及 win11） 的内部版本号仍然是 10.0。如果你在 Windows cmd 中输入 `wmic os get Caption,Version /value` 就可以看到：
![image](https://github.com/KomoriDev/nonebot-plugin-kawaii-status/assets/110453675/70809ee3-9903-4b0e-b764-f62737679f67)

> 还有希望可以添加自定义图片或者css的功能~

等学业减轻后会实现

**Comment by KomoriDev** [comment]
版本号显示问题目前不能修复，自定义图片后续会做
