### ISSUE TITLE
新增更多的细节数据

### ISSUE THREAD

**Issue by shengwang52005** [KomoriDev/nonebot-plugin-kawaii-status#16]
如题
建议新增Nonebot运行时间、系统运行时间、总收发信息数（可以用↑和↓）

**Comment by KomoriDev** [comment]
酱紫真的还可爱吗（
![Dashboard](https://github.com/KomoriDev/nonebot-plugin-kawaii-status/assets/110453675/93bc6dc9-11e6-454e-b34a-4f254424e204)

**Comment by shengwang52005** [comment]
还是可爱的（）
