### ISSUE TITLE
不支持 Python 3.9

### ISSUE THREAD

**Issue by aknyzsd** [KomoriDev/nonebot-plugin-kawaii-status#18]
![434e9f2abc97d51b64e0ff43a7b70864](https://github.com/user-attachments/assets/6bbc8f20-9ae1-411e-8f12-ca9f508f3ea5)
如图所示，佬有啥解决办法没qwq

**Comment by KomoriDev** [comment]
`TypeAlias` 是 3.10 的特性（

**Comment by aknyzsd** [comment]
好的感谢，此报错并不影响使用
那个问下有些bot账号并无返回头像和名称（或名称不对）是由于什么原因导致的

**Comment by aknyzsd** [comment]
> `TypeAlias` 是 3.10 的特性（

那佬有啥解决办法没，这个3.10指的是什么版本（我py应该是39）

**Comment by KomoriDev** [comment]
~~等我吃完饭~~我会适配 3.9

**Comment by aknyzsd** [comment]
感谢:D

**Comment by KomoriDev** [comment]
已发版，升级插件后再试试
