### ISSUE TITLE
Bug: CPU频率显示的小数位数过长

### ISSUE THREAD

**Issue by balh55y** [KomoriDev/nonebot-plugin-kawaii-status#2]
![cb90d6ba96e7e8d95c0c5b2a9f2ec59a](https://github.com/KomoriDev/nonebot-plugin-kawaii-status/assets/85926883/e3592a57-553f-421a-bd59-fd82a5474783)
可能是因为我在手机上跑的bot?

**Comment by KomoriDev** [comment]
已发版。更新后试试

**Comment by balh55y** [comment]
好了

**Comment by KomoriDev** [comment]
感谢反馈🤗
