### ISSUE TITLE
Windows版本识别问题

### ISSUE THREAD

**Issue by Jerry-Z07** [KomoriDev/nonebot-plugin-kawaii-status#28]
![QQ_1723563113076](https://github.com/user-attachments/assets/0fd07770-99d4-4a7a-921b-e1e55c1fcb4e)
如图，这应该是win11，插件识别结果是win10  
~~虽然好像没啥区别~~

**Comment by KomoriDev** [comment]
https://github.com/KomoriDev/nonebot-plugin-kawaii-status/issues/1#issuecomment-1985500635
