### ISSUE TITLE
CPU名称优化建议

### ISSUE THREAD

**Issue by starryrainy** [KomoriDev/nonebot-plugin-kawaii-status#6]
### cpu信息显示的低层硬件信息,可以把那边稍微优化下

安装cpuinfo库
`pip install py-cpuinfo`

drawer.py
`import cpuinfo`
`f"{truncate_string(cpuinfo.get_cpu_info()['brand_raw'])}",`

Ps:有些案例使用的是['brand'],但我从开源仓库里看到的是['brand_raw']
[https://github.com/sysfce2/python-py-cpuinfo](url)

**Comment by KomoriDev** [comment]
十分感谢，我曾想优化但没找到合适的替代品。我已发版，效果图也在 Readme 同步了
